name: "auth_class"

services:
  auth-api-service:
    image: "auth-api-img"
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./auth_service:/code
    networks:
      - auth-network

networks:
  auth-network:
